# Generated by Django 4.2.5 on 2023-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aboutme', models.TextField()),
            ],
        ),
    ]
