# Generated by Django 4.2.5 on 2023-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
