# Generated by Django 4.2.5 on 2023-10-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
